// Builds the app-icon concept SVGs (1024 canvas, Apple squircle tile baked in)
// and a preview page that shows each at Dock and Finder sizes on light and dark
// grounds. The SVGs are the sources of truth for the flat masters; the page is
// generated, never edited by hand.
//
//   node design/icon/build-icons.mjs <preview-dir>
//
// Writes design/icon/<Name>.svg for each concept and <preview-dir>/icon-preview.html.
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const previewDir = process.argv[2];
if (!previewDir) {
  console.error('usage: node build-icons.mjs <preview-dir>');
  process.exit(1);
}

// Apple's macOS icon tile: superellipse |x/a|^n + |y/a|^n = 1, 824 across on a
// 1024 canvas, exponent 5 (same as DuckLake Explorer's squircle-path.mjs).
function squirclePath() {
  const cx = 512, cy = 512, a = 412, n = 5, steps = 180;
  const pts = [];
  for (let i = 0; i < steps; i++) {
    const t = (i / steps) * Math.PI * 2;
    const c = Math.cos(t), s = Math.sin(t);
    const x = cx + Math.sign(c) * a * Math.pow(Math.abs(c), 2 / n);
    const y = cy + Math.sign(s) * a * Math.pow(Math.abs(s), 2 / n);
    pts.push(`${x.toFixed(1)} ${y.toFixed(1)}`);
  }
  return 'M ' + pts.join(' L ') + ' Z';
}
const SQUIRCLE = squirclePath();

// Sheet palette (DESIGN-TOKENS.md).
const day = { bg: '#F2F4F0', panel: '#FAFBF8', line: '#D6DBD2', line2: '#BEC5BA', grat: '#C5D3E2', water: '#DCE7F0', ink: '#222A26', muted2: '#8A948E', accent: '#B8236B', accentSoft: 'rgba(184,35,107,0.09)' };
const night = { bg: '#1A2128', bg2: '#11161B', panel: '#212930', line2: '#445362', grat: '#34506A', water: '#22303D', ink: '#E7EAE6', muted2: '#7B867F', accent: '#EA6AA6', accentSoft: 'rgba(234,106,166,0.14)' };

// Deterministic sample points, clustered like real addresses.
function samplePoints(box, seedStart) {
  let seed = seedStart;
  const rnd = () => { seed = (seed * 1103515245 + 12345) % 2147483648; return seed / 2147483648; };
  const towns = [[0.26, 0.3], [0.7, 0.4], [0.52, 0.76], [0.8, 0.8]];
  const pts = [];
  for (let i = 0; i < 44; i++) {
    const t = towns[i % towns.length];
    const spread = i % 6 === 0 ? 0.42 : 0.16;
    const x = t[0] + (rnd() - 0.5) * spread;
    const y = t[1] + (rnd() - 0.5) * spread * 1.1;
    if (x > 0.06 && x < 0.94 && y > 0.06 && y < 0.94) {
      pts.push([box.x + x * box.w, box.y + y * box.h]);
    }
  }
  return pts;
}

function circles(pts, r, fill) {
  return pts.map(([x, y]) => `<circle cx="${x.toFixed(0)}" cy="${y.toFixed(0)}" r="${r}" fill="${fill}"/>`).join('\n      ');
}

// Grid lines across a box, every `step`, starting at `offset` from the box origin.
function graticule(box, step, offset, stroke, width) {
  const d = [];
  for (let x = box.x + offset; x < box.x + box.w; x += step) d.push(`M${x} ${box.y}V${box.y + box.h}`);
  for (let y = box.y + offset; y < box.y + box.h; y += step) d.push(`M${box.x} ${y}H${box.x + box.w}`);
  return `<path d="${d.join('')}" stroke="${stroke}" stroke-width="${width}" fill="none"/>`;
}

function footprint(box, p, strokeW, dash) {
  return `<rect x="${box.x}" y="${box.y}" width="${box.w}" height="${box.h}" fill="${p.accentSoft}" stroke="${p.accent}" stroke-width="${strokeW}" stroke-dasharray="${dash}" stroke-linecap="butt"/>`;
}

function svgDoc(name, comment, defs, body) {
  return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1024 1024" width="1024" height="1024">
  <!-- ArcGIS Explorer app icon concept "${name}". ${comment}
       Flat master: Apple's macOS squircle tile (824pt on a 1024pt canvas) is baked in.
       Generated by design/icon/build-icons.mjs; edit the script, not this file. -->
  <defs>
    <path id="squircle" d="${SQUIRCLE}"/>
    <clipPath id="tile"><use xlink:href="#squircle"/></clipPath>
    ${defs}
  </defs>
  <g clip-path="url(#tile)">
    ${body}
  </g>
</svg>
`;
}

// A · Footprint (day): the tile is the sheet.
function conceptA() {
  const p = day;
  const tile = { x: 0, y: 0, w: 1024, h: 1024 };
  const fp = { x: 318, y: 286, w: 458, h: 436 };
  const pts = samplePoints(fp, 41);
  const body = `<rect width="1024" height="1024" fill="#EDEFE9"/>
    ${graticule(tile, 160, 72, p.grat, 4)}
    <path d="M0 790 C 130 760 230 800 340 828 S 560 900 700 878 S 900 826 1024 846 V1024 H0 Z" fill="${p.water}"/>
    ${footprint(fp, p, 16, '46 30')}
    <g>
      ${circles(pts, 13, p.accent)}
    </g>`;
  return svgDoc('A · Footprint', 'The tile is the survey sheet: graticule, a corner of water, and the layer footprint with its sample.', '', body);
}

// B · Sheet on the desk (night): a paper sheet with margins and ticks on a slate tile.
function conceptB() {
  const p = night;
  const sheet = { x: 156, y: 156, w: 712, h: 712 };
  const map = { x: 202, y: 202, w: 620, h: 620 };
  const fp = { x: 350, y: 316, w: 380, h: 360 };
  const pts = samplePoints(fp, 77);
  const ticks = [];
  for (let x = map.x + 96; x < map.x + map.w; x += 96) ticks.push(`M${x} ${sheet.y + 14}V${map.y - 6}`);
  for (let y = map.y + 96; y < map.y + map.h; y += 96) ticks.push(`M${sheet.x + 14} ${y}H${map.x - 6}`);
  const defs = `<linearGradient id="ground" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${p.bg}"/><stop offset="1" stop-color="${p.bg2}"/></linearGradient>
    <filter id="soft" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="18"/></filter>
    <clipPath id="map"><rect x="${map.x}" y="${map.y}" width="${map.w}" height="${map.h}"/></clipPath>`;
  const body = `<rect width="1024" height="1024" fill="url(#ground)"/>
    <rect x="${sheet.x}" y="${sheet.y + 26}" width="${sheet.w}" height="${sheet.h}" rx="26" fill="#000" opacity="0.45" filter="url(#soft)"/>
    <rect x="${sheet.x}" y="${sheet.y}" width="${sheet.w}" height="${sheet.h}" rx="26" fill="${day.bg}"/>
    <path d="${ticks.join('')}" stroke="${day.muted2}" stroke-width="5" fill="none"/>
    <g clip-path="url(#map)">
      <rect x="${map.x}" y="${map.y}" width="${map.w}" height="${map.h}" fill="${day.panel}"/>
      ${graticule(map, 96, 0, day.grat, 4)}
      <path d="M${map.x} 700 C 300 670 380 700 470 730 S 640 790 740 770 S 820 740 ${map.x + map.w} 760 V${map.y + map.h} H${map.x} Z" fill="${day.water}"/>
    </g>
    <rect x="${map.x}" y="${map.y}" width="${map.w}" height="${map.h}" fill="none" stroke="${day.line2}" stroke-width="4"/>
    ${footprint(fp, day, 14, '40 26')}
    <g>
      ${circles(pts, 12, day.accent)}
    </g>`;
  return svgDoc('B · Sheet', 'A paper map sheet with margins and ticks lying on the night slate; the footprint and sample drawn on it.', defs, body);
}

// C · Pulled layer (night): the front sheet of a stack lifted away.
function conceptC() {
  const p = night;
  const w = 500, h = 580, rx = 30;
  const sheets = [
    { x: 196, y: 332, fill: '#C9D0C8' },
    { x: 246, y: 282, fill: '#DEE2DC' },
  ];
  const front = { x: 330, y: 132 };
  const map = { x: front.x, y: front.y, w, h };
  const fp = { x: front.x + 92, y: front.y + 120, w: 316, h: 320 };
  const pts = samplePoints(fp, 19);
  const defs = `<linearGradient id="ground" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${p.bg}"/><stop offset="1" stop-color="${p.bg2}"/></linearGradient>
    <filter id="soft" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="16"/></filter>
    <clipPath id="front"><rect x="${front.x}" y="${front.y}" width="${w}" height="${h}" rx="${rx}"/></clipPath>`;
  const back = sheets.map(s => `<rect x="${s.x}" y="${s.y + 22}" width="${w}" height="${h}" rx="${rx}" fill="#000" opacity="0.4" filter="url(#soft)"/>
    <rect x="${s.x}" y="${s.y}" width="${w}" height="${h}" rx="${rx}" fill="${s.fill}"/>
    ${graticule({ x: s.x, y: s.y, w, h }, 96, 48, 'rgba(34,42,38,0.10)', 4)}`).join('\n    ');
  const body = `<rect width="1024" height="1024" fill="url(#ground)"/>
    ${back}
    <rect x="${front.x}" y="${front.y + 28}" width="${w}" height="${h}" rx="${rx}" fill="#000" opacity="0.5" filter="url(#soft)"/>
    <g clip-path="url(#front)">
      <rect x="${front.x}" y="${front.y}" width="${w}" height="${h}" fill="${day.bg}"/>
      ${graticule(map, 96, 48, day.grat, 4)}
      <path d="M${front.x} 560 C 420 540 480 570 560 600 S 720 650 ${front.x + w} 620 V${front.y + h} H${front.x} Z" fill="${day.water}"/>
    </g>
    ${footprint(fp, day, 14, '40 26')}
    <g>
      ${circles(pts, 11, day.accent)}
    </g>`;
  return svgDoc('C · Pulled layer', 'Three sheets from a server; the front one is lifted away carrying its footprint. Extraction as a gesture.', defs, body);
}

// D · Locator (night): the tree's locator glyph, large and pure.
function conceptD() {
  const p = night;
  const frame = { x: 192, y: 258, w: 640, h: 508 };
  const ext = { x: 348, y: 390, w: 320, h: 250 };
  const defs = `<linearGradient id="ground" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${p.bg}"/><stop offset="1" stop-color="${p.bg2}"/></linearGradient>`;
  const body = `<rect width="1024" height="1024" fill="url(#ground)"/>
    <rect x="${frame.x}" y="${frame.y}" width="${frame.w}" height="${frame.h}" rx="44" fill="none" stroke="${p.ink}" stroke-width="44"/>
    <rect x="${ext.x}" y="${ext.y}" width="${ext.w}" height="${ext.h}" rx="12" fill="${p.accent}"/>`;
  return svgDoc('D · Locator', 'The extent locator from the tree, large and pure: the server frame, the layer inside it.', defs, body);
}

const concepts = [
  { key: 'A', file: 'A-footprint.svg', name: 'A · Footprint', svg: conceptA(), why: 'The tile is the sheet. It is the Map tab in miniature: graticule, a corner of water, the dashed footprint and its sample.', tradeoff: 'A pale tile in a Dock of saturated icons; it reads quiet rather than loud.' },
  { key: 'B', file: 'B-sheet.svg', name: 'B · Sheet', svg: conceptB(), why: 'A paper map sheet with margins and ticks, lying on the night slate. The marginalia are the signature.', tradeoff: 'The ticks vanish below 64px; at Finder sizes it is a pale square with a magenta box.' },
  { key: 'C', file: 'C-pulled-layer.svg', name: 'C · Pulled layer', svg: conceptC(), why: 'Three sheets from a server, the front one lifted away with its footprint. The only concept that shows what the app does: extraction.', tradeoff: 'Busiest silhouette; the stack can read as a generic layers glyph.' },
  { key: 'D', file: 'D-locator.svg', name: 'D · Locator', svg: conceptD(), why: 'The tree locator glyph, large and pure: the server frame, the layer inside it. Reads at 16px.', tradeoff: 'Abstract; nothing says map until you know the app.' },
];

// Inline an SVG into the page with ids namespaced per concept and the fixed size removed.
function inlineSvg(key, svg) {
  return svg
    .replace(/ width="1024" height="1024"/, '')
    .replace(/id="([^"]+)"/g, `id="${key}-$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#${key}-$1)`)
    .replace(/xlink:href="#([^"]+)"/g, `xlink:href="#${key}-$1"`)
    .replace(/<!--[\s\S]*?-->/, '');
}

const sizes = [128, 64, 32, 16];
const rows = concepts.map(c => {
  const art = inlineSvg(c.key, c.svg);
  return `<section class="concept">
    <div class="big">${art}</div>
    <div class="text">
      <h2>${c.name}</h2>
      <p>${c.why}</p>
      <p class="trade">${c.tradeoff}</p>
    </div>
    <div class="sizes">${sizes.map(s => `<div class="sz" style="width:${s}px;height:${s}px">${art}</div>`).join('')}</div>
  </section>`;
}).join('\n');

function dock(theme) {
  const items = concepts.map(c => `<div class="dock-item">${inlineSvg(c.key + theme, c.svg)}</div>`).join('');
  return `<div class="dock ${theme}"><div class="dock-item ghost"></div>${items}<div class="dock-item ghost"></div></div>`;
}

const page = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ArcGIS Explorer Icon</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600;700&display=swap">
<style>
  :root { --bg: #E9EAE6; --ink: #222A26; --muted: #5E6863; --dock: rgba(255,255,255,.55); --dock-line: rgba(0,0,0,.08); }
  body { margin: 0; background: var(--bg); color: var(--ink); font-family: "Cabin", "Gill Sans", "Helvetica Neue", sans-serif; }
  .wrap { max-width: 1240px; margin: 0 auto; padding: 32px 24px 60px; }
  h1 { font-size: 22px; font-weight: 700; margin: 0 0 4px; }
  .lede { color: var(--muted); font-size: 14px; margin: 0 0 28px; max-width: 720px; line-height: 1.5; }
  .strip { border-radius: 16px; padding: 24px; margin-bottom: 28px; }
  .strip.light { background: #F1F2EE; }
  .strip.dark { background: #26292E; color: #E7EAE6; --muted: #A2ACA6; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(270px, 1fr)); gap: 28px; }
  .concept { display: flex; flex-direction: column; gap: 14px; }
  .big { width: 256px; height: 256px; }
  .big svg, .sz svg, .dock-item svg { width: 100%; height: 100%; display: block; filter: drop-shadow(0 1.5px 3px rgba(0,0,0,.22)); }
  .sizes { display: flex; align-items: flex-end; gap: 14px; height: 128px; }
  h2 { font-size: 15px; font-weight: 700; margin: 0 0 4px; }
  .text p { margin: 0; font-size: 13px; line-height: 1.45; color: var(--muted); max-width: 300px; }
  .text .trade { margin-top: 4px; }
  .dock { display: flex; gap: 10px; padding: 10px; border-radius: 22px; background: var(--dock); border: 1px solid var(--dock-line); width: max-content; margin: 18px auto 0; }
  .dock.dark { --dock: rgba(40,42,48,.85); --dock-line: rgba(255,255,255,.08); }
  .dock-item { width: 64px; height: 64px; }
  .dock-item.ghost { border-radius: 14px; background: rgba(120,125,120,.35); width: 52px; height: 52px; margin: 6px; }
  .label { font-size: 12px; color: var(--muted); text-align: center; margin-top: 8px; }
</style>
</head>
<body>
<div class="wrap">
  <h1>ArcGIS Explorer app icon</h1>
  <p class="lede">Four concepts in the Sheet language, each on Apple's squircle tile at Dock (128, 64), sidebar (32) and Finder list (16) sizes. The two Dock strips show them beside neighbours on a light and a dark desktop.</p>
  <div class="strip light">
    <div class="grid">${rows}</div>
    ${dock('light')}
    <div class="label">Light desktop, 64px</div>
  </div>
  <div class="strip dark">
    ${dock('dark')}
    <div class="label">Dark desktop, 64px</div>
  </div>
</div>
</body>
</html>
`;

// The same page as a fragment for publishing as an Artifact (the host supplies the
// document skeleton and paints its own ground, so the page tokens follow its theme).
const artifactPage = `<title>ArcGIS Explorer Icon</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600;700&display=swap">
<style>
  :root { --bg: #E9EAE6; --ink: #222A26; --muted: #5E6863; --dock: rgba(255,255,255,.55); --dock-line: rgba(0,0,0,.08); }
  @media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { --bg: #14181D; --ink: #E7EAE6; --muted: #A2ACA6; } }
  :root[data-theme="dark"] { --bg: #14181D; --ink: #E7EAE6; --muted: #A2ACA6; }
  body { margin: 0; background: var(--bg); color: var(--ink); font-family: "Cabin", "Gill Sans", "Helvetica Neue", sans-serif; }
  .wrap { max-width: 1240px; margin: 0 auto; padding-block: 32px 60px; padding-inline: 24px; }
  h1 { font-size: 22px; font-weight: 700; margin: 0 0 4px; }
  .lede { color: var(--muted); font-size: 14px; margin: 0 0 28px; max-width: 720px; line-height: 1.5; }
  .strip { border-radius: 16px; padding: 24px; margin-bottom: 28px; }
  .strip.light { background: #F1F2EE; color: #222A26; --muted: #5E6863; }
  .strip.dark { background: #26292E; color: #E7EAE6; --muted: #A2ACA6; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(270px, 1fr)); gap: 28px; }
  .concept { display: flex; flex-direction: column; gap: 14px; }
  .big { width: 256px; max-width: 100%; aspect-ratio: 1; }
  .big svg, .sz svg, .dock-item svg { width: 100%; height: 100%; display: block; filter: drop-shadow(0 1.5px 3px rgba(0,0,0,.22)); }
  .sizes { display: flex; align-items: flex-end; gap: 14px; height: 128px; }
  h2 { font-size: 15px; font-weight: 700; margin: 0 0 4px; }
  .text p { margin: 0; font-size: 13px; line-height: 1.45; color: var(--muted); max-width: 300px; }
  .text .trade { margin-top: 4px; }
  .dock { display: flex; gap: 10px; padding: 10px; border-radius: 22px; background: var(--dock); border: 1px solid var(--dock-line); width: max-content; max-width: 100%; margin: 18px auto 0; overflow-x: auto; }
  .dock.dark { --dock: rgba(40,42,48,.85); --dock-line: rgba(255,255,255,.08); }
  .dock-item { width: 64px; height: 64px; flex: 0 0 64px; }
  .dock-item.ghost { border-radius: 14px; background: rgba(120,125,120,.35); width: 52px; height: 52px; flex-basis: 52px; margin: 6px; }
  .label { font-size: 12px; color: var(--muted); text-align: center; margin-top: 8px; }
</style>
<div class="wrap">
  <h1>ArcGIS Explorer app icon</h1>
  <p class="lede">Four concepts in the Sheet language, each on Apple's squircle tile at Dock (128, 64), sidebar (32) and Finder list (16) sizes. The two Dock strips show them beside neighbours on a light and a dark desktop.</p>
  <div class="strip light">
    <div class="grid">${rows}</div>
    ${dock('light')}
    <div class="label">Light desktop, 64px</div>
  </div>
  <div class="strip dark">
    ${dock('dark')}
    <div class="label">Dark desktop, 64px</div>
  </div>
</div>
`;

await mkdir(previewDir, { recursive: true });
for (const c of concepts) await writeFile(join(here, c.file), c.svg);
await writeFile(join(previewDir, 'icon-preview.html'), page);
await writeFile(join(previewDir, 'arcgis-explorer-icon.html'), artifactPage);
console.log(`wrote ${concepts.length} concept SVGs to ${here}, icon-preview.html and arcgis-explorer-icon.html to ${previewDir}`);
