// Mechanics for building macOS app-icon artwork as SVG, reviewing it at real sizes,
// and drawing real geography on it. No design decisions live here: a concepts module
// (see build-icons.mjs) supplies the artwork; this file supplies the tools.
//
// Exports
//   SQUIRCLE, squirclePath()      Apple's macOS icon tile as an SVG path (824pt on 1024)
//   svgDoc(name, comment, defs, body)   a 1024px flat master with the tile clip baked in
//   loadFeature(file)             GeoJSON rows from geography.sql -> one MultiPolygon
//   bboxOf, windowFor, project, pathFor, extentRect   lon/lat -> tile px, equal scale
//   graticulePath(box, step, offset)    grid lines across a box
//   hexToRgba(hex, alpha)
//   buildPreview(concepts, previewDir)  writes icon-preview.html (standalone) and
//                                       arcgis-explorer-icon.html (Artifact fragment)
//   writeConcepts(concepts, dir)        writes each concept's SVG master
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

// ---- Tile ------------------------------------------------------------------

// Apple's macOS icon tile: superellipse |x/a|^n + |y/a|^n = 1, 824 across on a
// 1024 canvas, exponent 5 (same as DuckLake Explorer's squircle-path.mjs). Only the
// flat masters need it; an Icon Composer bundle is masked by the system.
export function squirclePath() {
  const cx = 512, cy = 512, a = 412, n = 5, steps = 180;
  const pts = [];
  for (let i = 0; i < steps; i++) {
    const t = (i / steps) * Math.PI * 2;
    const c = Math.cos(t), s = Math.sin(t);
    const x = cx + Math.sign(c) * a * Math.pow(Math.abs(c), 2 / n);
    const y = cy + Math.sign(s) * a * Math.pow(Math.abs(s), 2 / n);
    pts.push(`${x.toFixed(1)} ${y.toFixed(1)}`);
  }
  return 'M ' + pts.join(' L ') + ' Z';
}
export const SQUIRCLE = squirclePath();

// A 1024px flat master: everything in `body` is clipped to the tile. `defs` may add
// filters, gradients and clip paths. Keep Icon Composer layers simpler than this
// (no filters, masks or text) when the design is split into layers later.
export function svgDoc(name, comment, defs, body) {
  return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1024 1024" width="1024" height="1024">
  <!-- ArcGIS Explorer app icon "${name}". ${comment}
       Flat master: Apple's macOS squircle tile (824pt on a 1024pt canvas) is baked in.
       Generated by design/icon/build-icons.mjs; edit the concepts module, not this file. -->
  <defs>
    <path id="squircle" d="${SQUIRCLE}"/>
    <clipPath id="tile"><use xlink:href="#squircle"/></clipPath>
    ${defs}
  </defs>
  <g clip-path="url(#tile)">
    ${body}
  </g>
</svg>
`;
}

// ---- Geography -------------------------------------------------------------

// Rows written by geography.sql: [{ area, geojson }]. All parts become one feature.
export async function loadFeature(file) {
  const geo = JSON.parse(await readFile(file, 'utf8'));
  const feature = { type: 'MultiPolygon', coordinates: geo.flatMap(f => f.geojson.type === 'Polygon' ? [f.geojson.coordinates] : f.geojson.coordinates) };
  if (feature.coordinates.length === 0) throw new Error(`${file} is empty; re-run duckdb -f design/icon/geography.sql`);
  return feature;
}

export function rings(geojson) {
  if (geojson.type === 'Polygon') return geojson.coordinates;
  if (geojson.type === 'MultiPolygon') return geojson.coordinates.flat();
  return [];
}

export function bboxOf(geojson) {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const ring of rings(geojson)) for (const [x, y] of ring) {
    if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y;
  }
  return { x0, y0, x1, y1 };
}

// A window onto the map: the feature's bounding box is centred in `box` and spans
// `featH` of its height. Equal scale in x and y (equirectangular corrected by cos of
// the mid latitude), so shapes keep their proportions. `shift` moves the content left
// by that fraction of the box width, for sheets whose right edge is clipped.
export function windowFor(box, featH, feature, shift = 0) {
  const fb = bboxOf(feature);
  const midLat = (fb.y0 + fb.y1) / 2;
  const k = Math.cos(midLat * Math.PI / 180);
  const latSpan = (fb.y1 - fb.y0) / featH;
  const scale = box.h / latSpan;                // px per degree of latitude
  const lonSpan = box.w / (scale * k);
  const lonCentre = (fb.x0 + fb.x1) / 2 + shift * lonSpan;
  return { lon0: lonCentre - lonSpan / 2, latTop: midLat + latSpan / 2, k, scale, box };
}

export function project(win) {
  return ([lon, lat]) => [win.box.x + (lon - win.lon0) * win.k * win.scale, win.box.y + (win.latTop - lat) * win.scale];
}

export function pathFor(geojson, proj) {
  return rings(geojson).map(r => 'M' + r.map(pt => { const [x, y] = proj(pt); return `${x.toFixed(1)} ${y.toFixed(1)}`; }).join('L') + 'Z').join('');
}

// The projected bounding box of any lon/lat polygon, as a rect in tile px.
export function extentRect(geojson, proj) {
  const b = bboxOf(geojson);
  const [x0, y0] = proj([b.x0, b.y1]);
  const [x1, y1] = proj([b.x1, b.y0]);
  return { x: x0, y: y0, w: x1 - x0, h: y1 - y0 };
}

// Grid lines across a box, every `step`, starting `offset` in from the box origin.
export function graticulePath(box, step, offset = step / 2) {
  const d = [];
  for (let x = box.x + offset; x < box.x + box.w; x += step) d.push(`M${x} ${box.y}V${box.y + box.h}`);
  for (let y = box.y + offset; y < box.y + box.h; y += step) d.push(`M${box.x} ${y}H${box.x + box.w}`);
  return d.join('');
}

export function hexToRgba(hex, alpha) {
  const n = parseInt(hex.slice(1), 16);
  return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${alpha})`;
}

// ---- Preview page ----------------------------------------------------------

// Inline an SVG into the page with ids namespaced per concept and the fixed size removed.
function inlineSvg(key, svg) {
  return svg
    .replace(/ width="1024" height="1024"/, '')
    .replace(/id="([^"]+)"/g, `id="${key}-$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#${key}-$1)`)
    .replace(/xlink:href="#([^"]+)"/g, `xlink:href="#${key}-$1"`)
    .replace(/<!--[\s\S]*?-->/, '');
}

const sizes = [128, 64, 32, 16];

function dock(theme, concepts) {
  const cells = concepts.map(c => `<div class="dock-item">${inlineSvg(c.key + theme, c.svg)}</div>`).join('');
  return `<div class="dock ${theme}"><div class="dock-item ghost"></div>${cells}<div class="dock-item ghost"></div></div>`;
}

const css = `
  body { margin: 0; background: var(--bg); color: var(--ink); font-family: "Cabin", "Gill Sans", "Helvetica Neue", sans-serif; }
  .wrap { max-width: 1240px; margin: 0 auto; padding-block: 32px 60px; padding-inline: 24px; }
  h1 { font-size: 22px; font-weight: 700; margin: 0 0 4px; }
  .lede { color: var(--muted); font-size: 14px; margin: 0 0 28px; max-width: 720px; line-height: 1.5; }
  .strip { border-radius: 16px; padding: 24px; margin-bottom: 28px; }
  .strip.light { background: #F1F2EE; color: #222A26; --muted: #5E6863; }
  .strip.dark { background: #26292E; color: #E7EAE6; --muted: #A2ACA6; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 28px; }
  .concept { display: flex; flex-direction: column; gap: 14px; }
  .big { width: 260px; max-width: 100%; aspect-ratio: 1; }
  .big svg, .sz svg, .dock-item svg { width: 100%; height: 100%; display: block; filter: drop-shadow(0 1.5px 3px rgba(0,0,0,.22)); }
  .sizes { display: flex; align-items: flex-end; gap: 14px; height: 128px; }
  h2 { font-size: 15px; font-weight: 700; margin: 0 0 4px; }
  .text p { margin: 0; font-size: 13px; line-height: 1.45; color: var(--muted); max-width: 320px; }
  .text .trade { margin-top: 4px; }
  .dock { display: flex; gap: 10px; padding: 10px; border-radius: 22px; background: var(--dock); border: 1px solid var(--dock-line); width: max-content; max-width: 100%; margin: 18px auto 0; overflow-x: auto; }
  .dock.dark { --dock: rgba(40,42,48,.85); --dock-line: rgba(255,255,255,.08); }
  .dock-item { width: 64px; height: 64px; flex: 0 0 64px; }
  .dock-item.ghost { border-radius: 14px; background: rgba(120,125,120,.35); width: 52px; height: 52px; flex-basis: 52px; margin: 6px; }
  .label { font-size: 12px; color: var(--muted); text-align: center; margin-top: 8px; }
`;

const fontLink = `<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600;700&display=swap">`;

// Writes icon-preview.html (a standalone page for a LAN preview server) and
// arcgis-explorer-icon.html (a fragment for the Artifact tool, theme-aware).
// `concepts` is [{ key, name, svg, why, tradeoff }]; `lede` is the page's one-line brief.
export async function buildPreview(concepts, previewDir, lede = '') {
  const rows = concepts.map(c => {
    const art = inlineSvg(c.key, c.svg);
    return `<section class="concept">
    <div class="big">${art}</div>
    <div class="text">
      <h2>${c.name}</h2>
      <p>${c.why ?? ''}</p>
      <p class="trade">${c.tradeoff ?? ''}</p>
    </div>
    <div class="sizes">${sizes.map(s => `<div class="sz" style="width:${s}px;height:${s}px">${art}</div>`).join('')}</div>
  </section>`;
  }).join('\n');

  const content = `<div class="wrap">
  <h1>ArcGIS Explorer app icon</h1>
  <p class="lede">${lede}</p>
  <div class="strip light">
    <div class="grid">${rows}</div>
    ${dock('light', concepts)}
    <div class="label">Light desktop, 64px</div>
  </div>
  <div class="strip dark">
    ${dock('dark', concepts)}
    <div class="label">Dark desktop, 64px</div>
  </div>
</div>
`;

  const page = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ArcGIS Explorer Icon</title>
${fontLink}
<style>
  :root { --bg: #E9EAE6; --ink: #222A26; --muted: #5E6863; --dock: rgba(255,255,255,.55); --dock-line: rgba(0,0,0,.08); }
${css}
</style>
</head>
<body>
${content}
</body>
</html>
`;

  const artifactPage = `<title>ArcGIS Explorer Icon</title>
${fontLink}
<style>
  :root { --bg: #E9EAE6; --ink: #222A26; --muted: #5E6863; --dock: rgba(255,255,255,.55); --dock-line: rgba(0,0,0,.08); }
  @media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { --bg: #14181D; --ink: #E7EAE6; --muted: #A2ACA6; } }
  :root[data-theme="dark"] { --bg: #14181D; --ink: #E7EAE6; --muted: #A2ACA6; }
${css}
</style>
${content}`;

  await mkdir(previewDir, { recursive: true });
  await writeFile(join(previewDir, 'icon-preview.html'), page);
  await writeFile(join(previewDir, 'arcgis-explorer-icon.html'), artifactPage);
}

// Writes each concept's SVG master as <dir>/<file>.
export async function writeConcepts(concepts, dir) {
  await mkdir(dir, { recursive: true });
  for (const c of concepts) await writeFile(join(dir, c.file), c.svg);
}
