// Mechanics for building macOS app-icon artwork as SVG, reviewing it at real sizes,
// and drawing real geography on it. No design decisions live here: a concepts module
// (see build-icons.mjs) supplies the artwork; this file supplies the tools.
//
// Exports
//   SQUIRCLE, squirclePath()      Apple's macOS icon tile as an SVG path (824pt on 1024)
//   TILE, BUNDLE_SCALE            the tile's box on the canvas; canvas/tile ratio
//   svgDoc(name, comment, defs, body)   a 1024px flat master with the tile clip baked in
//   loadFeature(file, parts)      GeoJSON rows from geography.sql -> one MultiPolygon
//   bboxOf, windowFor, project, pathFor, extentRect   lon/lat -> tile px, equal scale
//   projectedRings, ringsToPath, clipRingToConvex, circlePolygon   clipping without clipPath
//   graticulePath, graticuleRects, graticuleChords   grid lines across a box or a circle
//   rectPath, rectRingPath, dashedRectRings, dashedRectPath, circlePath, ringPath,
//   rectWithHolePath, rotatedRectRing, neatlineTicks   filled shapes, no strokes needed
//   hexToRgba(hex, alpha), hexToSrgb(hex)
//   flatMaster(concept), layerSvg(layer), iconJson(concept), writeIconBundle(concept, dir)
//                                 a layered concept -> flat master and Icon Composer bundle
//   buildPreview(concepts, previewDir, lede, renders)  writes icon-preview.html (standalone)
//                                       and arcgis-explorer-icon.html (Artifact fragment)
//   writeConcepts(concepts, dir)        writes each concept's SVG master(s)
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

// ---- Tile ------------------------------------------------------------------

// Apple's macOS icon tile: superellipse |x/a|^n + |y/a|^n = 1, 824 across on a
// 1024 canvas, exponent 5 (same as DuckLake Explorer's squircle-path.mjs). Only the
// flat masters need it; an Icon Composer bundle is masked by the system.
export function squirclePath() {
  const cx = 512, cy = 512, a = 412, n = 5, steps = 180;
  const pts = [];
  for (let i = 0; i < steps; i++) {
    const t = (i / steps) * Math.PI * 2;
    const c = Math.cos(t), s = Math.sin(t);
    const x = cx + Math.sign(c) * a * Math.pow(Math.abs(c), 2 / n);
    const y = cy + Math.sign(s) * a * Math.pow(Math.abs(s), 2 / n);
    pts.push(`${x.toFixed(1)} ${y.toFixed(1)}`);
  }
  return 'M ' + pts.join(' L ') + ' Z';
}
export const SQUIRCLE = squirclePath();

// The tile's box on the 1024 canvas, and the factor that scales tile coordinates onto
// the full canvas for an Icon Composer layer (the system masks those itself).
export const TILE = { x: 100, y: 100, w: 824, h: 824 };
export const BUNDLE_SCALE = 1024 / 824;

// A 1024px flat master: everything in `body` is clipped to the tile. `defs` may add
// filters, gradients and clip paths. Keep Icon Composer layers simpler than this
// (no filters, masks or text) when the design is split into layers later.
export function svgDoc(name, comment, defs, body) {
  return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1024 1024" width="1024" height="1024">
  <!-- ArcGIS Explorer app icon "${name}". ${comment}
       Flat master: Apple's macOS squircle tile (824pt on a 1024pt canvas) is baked in.
       Generated by design/icon/build-icons.mjs; edit the concepts module, not this file. -->
  <defs>
    <path id="squircle" d="${SQUIRCLE}"/>
    <clipPath id="tile"><use xlink:href="#squircle"/></clipPath>
    ${defs}
  </defs>
  <g clip-path="url(#tile)">
    ${body}
  </g>
</svg>
`;
}

// ---- Geography -------------------------------------------------------------

// Rows written by geography.sql: [{ area, geojson }], largest first. The first `parts`
// rows become one feature (2 = Great Britain and Ireland, dropping the Outer Hebrides).
export async function loadFeature(file, parts = Infinity) {
  const geo = JSON.parse(await readFile(file, 'utf8')).slice(0, parts);
  const feature = { type: 'MultiPolygon', coordinates: geo.flatMap(f => f.geojson.type === 'Polygon' ? [f.geojson.coordinates] : f.geojson.coordinates) };
  if (feature.coordinates.length === 0) throw new Error(`${file} is empty; re-run duckdb -f design/icon/geography.sql`);
  return feature;
}

export function rings(geojson) {
  if (geojson.type === 'Polygon') return geojson.coordinates;
  if (geojson.type === 'MultiPolygon') return geojson.coordinates.flat();
  return [];
}

export function bboxOf(geojson) {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const ring of rings(geojson)) for (const [x, y] of ring) {
    if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y;
  }
  return { x0, y0, x1, y1 };
}

// A window onto the map: the feature's bounding box is centred in `box` and spans
// `featH` of its height. Equal scale in x and y (equirectangular corrected by cos of
// the mid latitude), so shapes keep their proportions. `shift` moves the content left
// by that fraction of the box width, for sheets whose right edge is clipped.
export function windowFor(box, featH, feature, shift = 0) {
  const fb = bboxOf(feature);
  const midLat = (fb.y0 + fb.y1) / 2;
  const k = Math.cos(midLat * Math.PI / 180);
  const latSpan = (fb.y1 - fb.y0) / featH;
  const scale = box.h / latSpan;                // px per degree of latitude
  const lonSpan = box.w / (scale * k);
  const lonCentre = (fb.x0 + fb.x1) / 2 + shift * lonSpan;
  return { lon0: lonCentre - lonSpan / 2, latTop: midLat + latSpan / 2, k, scale, box };
}

export function project(win) {
  return ([lon, lat]) => [win.box.x + (lon - win.lon0) * win.k * win.scale, win.box.y + (win.latTop - lat) * win.scale];
}

export function pathFor(geojson, proj) {
  return ringsToPath(projectedRings(geojson, proj));
}

// Rings in tile px (closing point dropped), ready for clipping.
export function projectedRings(geojson, proj) {
  return rings(geojson).map(r => {
    const pts = r.map(proj);
    const [x0, y0] = pts[0], [x1, y1] = pts[pts.length - 1];
    return x0 === x1 && y0 === y1 ? pts.slice(0, -1) : pts;
  });
}

export function ringsToPath(ringList) {
  return ringList.filter(r => r.length >= 3)
    .map(r => 'M' + r.map(([x, y]) => `${x.toFixed(1)} ${y.toFixed(1)}`).join('L') + 'Z').join('');
}

// Sutherland–Hodgman: the part of `ring` inside the convex polygon `clip`. Icon Composer
// layers must not use clipPath, so shapes are cut geometrically instead.
export function clipRingToConvex(ring, clip) {
  const sgn = Math.sign(polygonArea(clip));
  let out = ring.slice();
  for (let i = 0; i < clip.length && out.length; i++) {
    const a = clip[i], b = clip[(i + 1) % clip.length];
    const inside = p => sgn * ((b[0] - a[0]) * (p[1] - a[1]) - (b[1] - a[1]) * (p[0] - a[0])) >= 0;
    const input = out;
    out = [];
    for (let j = 0; j < input.length; j++) {
      const cur = input[j], prev = input[(j + input.length - 1) % input.length];
      const curIn = inside(cur), prevIn = inside(prev);
      if (curIn) {
        if (!prevIn) out.push(lineIntersection(prev, cur, a, b));
        out.push(cur);
      } else if (prevIn) {
        out.push(lineIntersection(prev, cur, a, b));
      }
    }
  }
  return out;
}

function lineIntersection(p, q, a, b) {
  const d = (p[0] - q[0]) * (a[1] - b[1]) - (p[1] - q[1]) * (a[0] - b[0]);
  const t = ((p[0] - a[0]) * (a[1] - b[1]) - (p[1] - a[1]) * (a[0] - b[0])) / d;
  return [p[0] + t * (q[0] - p[0]), p[1] + t * (q[1] - p[1])];
}

export function polygonArea(ring) {
  let s = 0;
  for (let i = 0; i < ring.length; i++) {
    const [x0, y0] = ring[i], [x1, y1] = ring[(i + 1) % ring.length];
    s += x0 * y1 - x1 * y0;
  }
  return s / 2;
}

export function circlePolygon(cx, cy, r, n = 96) {
  return Array.from({ length: n }, (_, i) => {
    const t = (i / n) * Math.PI * 2;
    return [cx + r * Math.cos(t), cy + r * Math.sin(t)];
  });
}

// The projected bounding box of any lon/lat polygon, as a rect in tile px.
export function extentRect(geojson, proj) {
  const b = bboxOf(geojson);
  const [x0, y0] = proj([b.x0, b.y1]);
  const [x1, y1] = proj([b.x1, b.y0]);
  return { x: x0, y: y0, w: x1 - x0, h: y1 - y0 };
}

// Grid lines across a box, every `step`, starting `offset` in from the box origin.
export function graticulePath(box, step, offset = step / 2) {
  const d = [];
  for (let x = box.x + offset; x < box.x + box.w; x += step) d.push(`M${x} ${box.y}V${box.y + box.h}`);
  for (let y = box.y + offset; y < box.y + box.h; y += step) d.push(`M${box.x} ${y}H${box.x + box.w}`);
  return d.join('');
}

// The same grid as filled rects `t` wide, for layers that cannot rely on strokes.
export function graticuleRects(box, step, offset = step / 2, t = 4) {
  const d = [];
  for (let x = box.x + offset; x < box.x + box.w; x += step) d.push(rectPath(x - t / 2, box.y, t, box.h));
  for (let y = box.y + offset; y < box.y + box.h; y += step) d.push(rectPath(box.x, y - t / 2, box.w, t));
  return d.join('');
}

// The grid cut to a circle: every line becomes a chord.
export function graticuleChords(cx, cy, radius, step, offset = step / 2, t = 4) {
  const d = [];
  for (let u = -radius + offset; u < radius; u += step) {
    const half = Math.sqrt(Math.max(0, radius * radius - u * u));
    if (half < t) continue;
    d.push(rectPath(cx + u - t / 2, cy - half, t, half * 2));
    d.push(rectPath(cx - half, cy + u - t / 2, half * 2, t));
  }
  return d.join('');
}

// ---- Filled shapes -----------------------------------------------------------
// Everything below is a filled path, so it renders identically in rsvg, a browser and
// Icon Composer, which cannot be trusted with strokes, dashes, masks or clipPath.

const r1 = n => Math.round(n * 10) / 10;

export function rectPath(x, y, w, h) {
  return `M${r1(x)} ${r1(y)}h${r1(w)}v${r1(h)}h${r1(-w)}Z`;
}

// A rectangular frame `t` thick: outer ring clockwise, inner counter-clockwise, so the
// nonzero rule leaves the middle open.
export function rectRingPath(x, y, w, h, t) {
  return `M${x} ${y}H${x + w}V${y + h}H${x}Z` + `M${x + t} ${y + t}V${y + h - t}H${x + w - t}V${y + t}Z`;
}

// A dashed rectangle as rects (rings of four points). The period is fitted to each side
// so that every corner carries a dash and the pattern is symmetric.
export function dashedRectRings(x, y, w, h, t, dash, gap) {
  const out = [];
  const rect = (rx, ry, rw, rh) => out.push([[rx, ry], [rx + rw, ry], [rx + rw, ry + rh], [rx, ry + rh]]);
  const edge = (len, emit) => {
    const n = Math.max(1, Math.round((len - dash) / (dash + gap)));
    const period = (len - dash) / n;
    for (let i = 0; i <= n; i++) emit(i * period, Math.min(dash, len - i * period));
  };
  edge(w, (s, l) => rect(x + s, y, l, t));
  edge(h, (s, l) => rect(x + w - t, y + s, t, l));
  edge(w, (s, l) => rect(x + w - s - l, y + h - t, l, t));
  edge(h, (s, l) => rect(x, y + h - s - l, t, l));
  return out;
}

export function dashedRectPath(x, y, w, h, t, dash, gap) {
  return ringsToPath(dashedRectRings(x, y, w, h, t, dash, gap));
}

// A circle as a path; `ccw` reverses the winding for cutting holes under the nonzero rule.
export function circlePath(cx, cy, r, ccw = false) {
  const s = ccw ? 0 : 1;
  return `M${cx - r} ${cy}A${r} ${r} 0 1 ${s} ${cx + r} ${cy}A${r} ${r} 0 1 ${s} ${cx - r} ${cy}Z`;
}

export function ringPath(cx, cy, rOuter, rInner) {
  return circlePath(cx, cy, rOuter) + circlePath(cx, cy, rInner, true);
}

export function rectWithHolePath(x, y, w, h, cx, cy, r) {
  return `M${x} ${y}H${x + w}V${y + h}H${x}Z` + circlePath(cx, cy, r, true);
}

// A w×h rect whose centre-left sits at distance `radius` from (cx, cy), rotated `deg`
// around (cx, cy); at 0° it points to the right. For ticks around a ring.
export function rotatedRectRing(cx, cy, radius, w, h, deg) {
  const a = (deg * Math.PI) / 180, c = Math.cos(a), s = Math.sin(a);
  return [[radius, -h / 2], [radius + w, -h / 2], [radius + w, h / 2], [radius, h / 2]]
    .map(([x, y]) => [cx + x * c - y * s, cy + x * s + y * c]);
}

// Ticks outside a rect's edges: `divisions` per side, corners skipped.
export function neatlineTicks(rect, divisions, len, t, offset = 0) {
  const d = [];
  for (let i = 1; i < divisions; i++) {
    const x = rect.x + (rect.w * i) / divisions, y = rect.y + (rect.h * i) / divisions;
    d.push(rectPath(x - t / 2, rect.y - offset - len, t, len));
    d.push(rectPath(x - t / 2, rect.y + rect.h + offset, t, len));
    d.push(rectPath(rect.x - offset - len, y - t / 2, len, t));
    d.push(rectPath(rect.x + rect.w + offset, y - t / 2, len, t));
  }
  return d.join('');
}

export function hexToRgba(hex, alpha) {
  const n = parseInt(hex.slice(1), 16);
  return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${alpha})`;
}

export function hexToSrgb(hex) {
  const n = parseInt(hex.slice(1), 16);
  const c = v => (v / 255).toFixed(5);
  return `srgb:${c((n >> 16) & 255)},${c((n >> 8) & 255)},${c(n & 255)},1.00000`;
}

// ---- Layered concepts --------------------------------------------------------
// A concept is { key, file, name, fill, layers, small?, shadow? } with `layers` bottom
// first, each { name, body, defs?, glass?, opacity?, flatOnly? } drawn in tile
// coordinates (824pt tile at 100,100 on the 1024 canvas). `fill` is a hex or
// { top, bottom } for a vertical gradient. The flat master and the Icon Composer
// bundle are both derived from it, so what the contact sheet shows is what actool
// compiles. `flatOnly` layers (hard shadows the bundle gets from its group shadow)
// are left out of the bundle.

function fillSpec(fill) {
  return typeof fill === 'string' ? { top: fill, bottom: fill } : fill;
}

export function flatMaster(concept, layers = concept.layers) {
  const { top, bottom } = fillSpec(concept.fill);
  const defs = `<linearGradient id="ground" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${top}"/><stop offset="1" stop-color="${bottom}"/></linearGradient>`
    + layers.map(l => l.defs ?? '').join('');
  const body = `<rect x="0" y="0" width="1024" height="1024" fill="url(#ground)"/>\n`
    + layers.map(l => `<g id="layer-${l.name}"${l.opacity != null ? ` opacity="${l.opacity}"` : ''}>${l.body}</g>`).join('\n');
  return svgDoc(concept.name, concept.comment ?? '', defs, body);
}

// One Icon Composer layer: the full canvas, tile coordinates scaled up 1024/824.
export function layerSvg(layer) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="1024px" height="1024px" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <title>${layer.name}</title>
  <defs>${layer.defs ?? ''}</defs>
  <g transform="scale(${BUNDLE_SCALE.toFixed(6)}) translate(-100 -100)"${layer.opacity != null ? ` opacity="${layer.opacity}"` : ''}>
    ${layer.body}
  </g>
</svg>
`;
}

// icon.json as Icon Composer writes it. Arrays are top-to-bottom, so the bottom-first
// layer list is reversed. One group; glass per layer.
export function iconJson(concept) {
  const { top, bottom } = fillSpec(concept.fill);
  const layers = concept.layers.filter(l => !l.flatOnly).reverse().map(l => ({
    glass: l.glass === true,
    hidden: false,
    'image-name': `${l.name}.svg`,
    name: l.name,
    opacity: 1,
  }));
  return JSON.stringify({
    fill: { 'linear-gradient': [hexToSrgb(top), hexToSrgb(bottom)] },
    groups: [{
      'blend-mode': 'normal',
      hidden: false,
      layers,
      lighting: 'individual',
      shadow: { kind: 'neutral', opacity: concept.shadow ?? 0.35 },
      specular: true,
      translucency: { enabled: false, value: 0.5 },
    }],
    'supported-platforms': { circles: ['watchOS'], squares: 'shared' },
  }, null, 2) + '\n';
}

// Writes <dir>/<Bundle>.icon/{icon.json, Assets/<layer>.svg} and returns the bundle path.
export async function writeIconBundle(concept, dir) {
  const bundle = join(dir, `${concept.bundle ?? concept.key}.icon`);
  await mkdir(join(bundle, 'Assets'), { recursive: true });
  await writeFile(join(bundle, 'icon.json'), iconJson(concept));
  for (const l of concept.layers.filter(l => !l.flatOnly)) {
    await writeFile(join(bundle, 'Assets', `${l.name}.svg`), layerSvg(l));
  }
  return bundle;
}

// ---- Preview page ----------------------------------------------------------

// Inline an SVG into the page with ids namespaced per concept and the fixed size removed.
function inlineSvg(key, svg) {
  return svg
    .replace(/ width="1024" height="1024"/, '')
    .replace(/id="([^"]+)"/g, `id="${key}-$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#${key}-$1)`)
    .replace(/xlink:href="#([^"]+)"/g, `xlink:href="#${key}-$1"`)
    .replace(/<!--[\s\S]*?-->/, '');
}

const sizes = [128, 64, 32, 16];

// Art for a given size: the hand-tuned small master at 32px and below when there is one.
function artFor(c, size) {
  return inlineSvg(size <= 32 && c.svgSmall ? `${c.key}-s` : c.key, size <= 32 && c.svgSmall ? c.svgSmall : c.svg);
}

// A 64px Dock strip. With `renders` (actool PNGs by key and pixel size) the 128px
// render is shown at 64px, which is what a Retina Dock displays.
function dock(theme, concepts, renders) {
  const cells = concepts.map(c => renders?.[c.key]?.[128]
    ? `<div class="dock-item"><img src="${renders[c.key][128]}" alt="${c.name} as macOS renders it"></div>`
    : `<div class="dock-item">${inlineSvg(c.key + theme, c.svg)}</div>`).join('');
  return `<div class="dock ${theme}"><div class="dock-item ghost"></div>${cells}<div class="dock-item ghost"></div></div>`;
}

// The actool renders of one concept, each @2x bitmap shown at half size (Retina).
function renderRow(c, renders) {
  const r = renders?.[c.key];
  if (!r) return '';
  return `<div class="sizes rendered">${sizes.map(s => r[s * 2]
    ? `<img src="${r[s * 2]}" alt="" style="width:${s}px;height:${s}px">`
    : '').join('')}</div>
    <div class="caption">Compiled by actool from the Icon Composer bundle, Liquid Glass applied</div>`;
}

const css = `
  body { margin: 0; background: var(--bg); color: var(--ink); font-family: "Cabin", "Gill Sans", "Helvetica Neue", sans-serif; }
  .wrap { max-width: 1240px; margin: 0 auto; padding-block: 32px 60px; padding-inline: 24px; }
  h1 { font-size: 22px; font-weight: 700; margin: 0 0 4px; }
  .lede { color: var(--muted); font-size: 14px; margin: 0 0 28px; max-width: 720px; line-height: 1.5; }
  .strip { border-radius: 16px; padding: 24px; margin-bottom: 28px; }
  .strip.light { background: #F1F2EE; color: #222A26; --muted: #5E6863; }
  .strip.dark { background: #26292E; color: #E7EAE6; --muted: #A2ACA6; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 28px; }
  .concept { display: flex; flex-direction: column; gap: 14px; }
  .big { width: 260px; max-width: 100%; aspect-ratio: 1; }
  .big svg, .sz svg, .dock-item svg { width: 100%; height: 100%; display: block; filter: drop-shadow(0 1.5px 3px rgba(0,0,0,.22)); }
  .sizes { display: flex; align-items: flex-end; gap: 14px; height: 128px; }
  .sizes img { display: block; }
  .caption { font-size: 11px; color: var(--muted); margin-top: -6px; }
  .dock-item img { width: 100%; height: 100%; display: block; }
  h2 { font-size: 15px; font-weight: 700; margin: 0 0 4px; }
  .text p { margin: 0; font-size: 13px; line-height: 1.45; color: var(--muted); max-width: 320px; }
  .text .trade { margin-top: 4px; }
  .dock { display: flex; gap: 10px; padding: 10px; border-radius: 22px; background: var(--dock); border: 1px solid var(--dock-line); width: max-content; max-width: 100%; margin: 18px auto 0; overflow-x: auto; }
  .dock.dark { --dock: rgba(40,42,48,.85); --dock-line: rgba(255,255,255,.08); }
  .dock-item { width: 64px; height: 64px; flex: 0 0 64px; }
  .dock-item.ghost { border-radius: 14px; background: rgba(120,125,120,.35); width: 52px; height: 52px; flex-basis: 52px; margin: 6px; }
  .label { font-size: 12px; color: var(--muted); text-align: center; margin-top: 8px; }
`;

const fontLink = `<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600;700&display=swap">`;

// Writes icon-preview.html (a standalone page for a LAN preview server) and
// arcgis-explorer-icon.html (a fragment for the Artifact tool, theme-aware).
// `concepts` is [{ key, name, svg, svgSmall?, why, tradeoff }]; `lede` is the page's
// one-line brief; `renders` is { [key]: { [px]: dataUri } } of actool output, optional.
export async function buildPreview(concepts, previewDir, lede = '', renders = null) {
  const rows = concepts.map(c => {
    const art = inlineSvg(c.key, c.svg);
    return `<section class="concept">
    <div class="big">${art}</div>
    <div class="text">
      <h2>${c.name}</h2>
      <p>${c.why ?? ''}</p>
      <p class="trade">${c.tradeoff ?? ''}</p>
    </div>
    <div class="sizes">${sizes.map(s => `<div class="sz" style="width:${s}px;height:${s}px">${artFor(c, s)}</div>`).join('')}</div>
    ${renders ? `<div class="caption">Flat master, ${c.svgSmall ? 'hand-tuned art at 32 and 16' : 'one master at every size'}</div>` : ''}
    ${renderRow(c, renders)}
  </section>`;
  }).join('\n');

  const content = `<div class="wrap">
  <h1>ArcGIS Explorer app icon</h1>
  <p class="lede">${lede}</p>
  <div class="strip light">
    <div class="grid">${rows}</div>
    ${dock('light', concepts, renders)}
    <div class="label">Light desktop, 64px${renders ? ', actool render' : ''}</div>
  </div>
  <div class="strip dark">
    ${dock('dark', concepts, renders)}
    <div class="label">Dark desktop, 64px${renders ? ', actool render' : ''}</div>
  </div>
</div>
`;

  const page = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ArcGIS Explorer Icon</title>
${fontLink}
<style>
  :root { --bg: #E9EAE6; --ink: #222A26; --muted: #5E6863; --dock: rgba(255,255,255,.55); --dock-line: rgba(0,0,0,.08); }
${css}
</style>
</head>
<body>
${content}
</body>
</html>
`;

  const artifactPage = `<title>ArcGIS Explorer Icon</title>
${fontLink}
<style>
  :root { --bg: #E9EAE6; --ink: #222A26; --muted: #5E6863; --dock: rgba(255,255,255,.55); --dock-line: rgba(0,0,0,.08); }
  @media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { --bg: #14181D; --ink: #E7EAE6; --muted: #A2ACA6; } }
  :root[data-theme="dark"] { --bg: #14181D; --ink: #E7EAE6; --muted: #A2ACA6; }
${css}
</style>
${content}`;

  await mkdir(previewDir, { recursive: true });
  await writeFile(join(previewDir, 'icon-preview.html'), page);
  await writeFile(join(previewDir, 'arcgis-explorer-icon.html'), artifactPage);
}

// Writes each concept's SVG master as <dir>/<file>, and the small master (32px and
// below) as <dir>/<file stem>-small.svg when the concept has one.
export async function writeConcepts(concepts, dir) {
  await mkdir(dir, { recursive: true });
  for (const c of concepts) {
    await writeFile(join(dir, c.file), c.svg);
    if (c.svgSmall) await writeFile(join(dir, c.file.replace(/\.svg$/, '-small.svg')), c.svgSmall);
  }
}

// Reads <rendersDir>/<key>-<px>.png for every concept and size into data URIs.
export async function loadRenders(concepts, rendersDir) {
  const out = {};
  for (const c of concepts) {
    out[c.key] = {};
    for (const px of [16, 32, 64, 128, 256, 512]) {
      try {
        const png = await readFile(join(rendersDir, `${c.key}-${px}.png`));
        out[c.key][px] = `data:image/png;base64,${png.toString('base64')}`;
      } catch (e) {
        if (e.code !== 'ENOENT') throw e;
      }
    }
    if (Object.keys(out[c.key]).length === 0) throw new Error(`no renders for ${c.key} in ${rendersDir}`);
  }
  return out;
}
